let help = {
  "solar-masses-btn": "The mass of the star in Solar masses. For habitable systems choose a mass between 0.6-1.4 for your habitable star.",
  "kg-masses-btn": "Mass of star in kg.",
  "solar-luminosity-btn": "How bright the star is in Solar luminosities.",
  "solar-diameter-btn": "Diameter of the star in solar diameters.",
  "km-diameter-btn": "Diameter of the star in km.",
  "solar-temp-btn": "The surface temperature of the star compared to that of the Suns.",
  "k-temp-btn": "The surface temperature of the star in Kelvin.",
  "solar-lifetime-btn": "The lifetime of the star in solar lifetimes.",
  "year-lifetime-btn": "The lifetime of the star in Earth years.",
  "inner-planet-btn": "How close to a star planets can be without being destroyed in AU.",
  "outer-planet-btn": "How far from a star planets can be without being lost in AU.",
  "inner-habitable-btn": "The inner limit of the habitable zone in AU.",
  "outer-habitable-btn": "The outer limit of the habitable zone in AU.",
  "frost-btn": "The distance from the star in AU where volatile compounds - including carbon dioxide and ammonia - will freeze.",
  "star-eccentrisity-btn":"How eliptical the orbit is. 1 is perfect circle. Should be between 0.4 and 0.7, lower is better.",
  "star-semi-major-btn":"The longest possible line from the center of the orbital path to the path itself.</br>This is mostly used for caculations, you probably don't care about it.",
  "star-avg-bary-btn":"The average distance between the star and the barycenter (the point between the two stars that they both orbit).",
  "star-max-bary-btn":"The maximum distance from the barycenter in AU",
  "star-min-bary-btn":"The minimum distance from the barycenter in AU",
  "star-avg-separation-btn":"The average separation between the two stars. Should be between 0.15 and 6 AU, closer is better.",
  "star-min-separation-btn":"The Farthest the two stars get appart.",
  "star-max-separation-btn":"The closest the two stars get.",
  "star-orbital-period-btn":"The time it takes for either star to complete an orbit around the center of mass of the system.</br>Both stars take the same amount of time to complete an orbit regardless of mass and eccentrisity.",
  "shared-inner-planet-btn":"How close to a star planets can be without being destroyed in AU",
  "shared-outer-planet-btn":"How far from a star planets can be without being lost in AU.",
  "shared-inner-habit-btn":"The inner limit of the habitable zone in AU.",
  "shared-outer-habit-btn":"The outer limit of the habitable zone in AU.",
  "shared-frost-btn":"The distance from the star in AU where volatile compounds - including carbon dioxide and ammonia - will freeze.",
  "shared-inner-death-btn":"The inner limit of the gravitationally unstable zone around the two stars.</br>NO PLANETS IN THE DEATH ZONE",
  "shared-outer-death-btn":"The outer limit of the gravitationally unstable zone around the two stars.</br>NO PLANETS IN THE DEATH ZONE",
  "planet-mass-btn":"Mass in Earth Masses. Habitable Planet should be between 0.1 and 3.5 Earth Masses.",
  "planet-mass-kg-btn":"Mass in Kg.",
  "planet-rad-btn":"Radius in Earth Radii. Habitable planet should be between 0.5 and 1.5 Earth Redii.",
  "planet-rad-km-btn":"Radius in Km.",
  "planet-gravity-btn":"Gravity in Earth Gravities. A habitable world should be between 0.4 and 1.6 times the gravity of Earth, play with the mass and radius to achieve this.",
  "planet-gravity-metric-btn":"Gravity in metric units.",
  "planet-density-btn":"Density relitive to that of Earths.",
  "planet-density-metric-btn":"Density in metric units.",
  "planet-escape-btn":"The velocity it takes to escape the planets gravity relitive to Earth's escape velocity.",
  "planet-escape-metric-btn":"The velocity it takes to escape the planets gravity in metric units.",
  "planet-circumference-btn":"The length of the equator relitive to Earth's.",
  "planet-circomference-km-btn":"The length of the equator in km.",
  "planet-surface-btn":"The planet's surface area relitive to that of Earth's.",
  "planet-surface-metric-btn":"The planet's surface area in metric units.",
  "planet-volume-btn":"The planet's volume relitive to that of Earth's.",
  "planet-volume-km-btn":"The planet's volume in metric units.",
  "planet-temp-btn":"The average temp accross the whole planet relitive to Earth's. Note, this is the winter and summer side of the planet, the polar regions to the equator.",
  "planet-temp-k-btn":"The average temp accross the whole planet in Kelvin. Note, this is the winter and summer side of the planet, the polar regions to the equator.",
  "planet-eccentricity-btn":"How much the orbit deviates from a perfect circle. Needs to be between 0 and 1.</br>Habitable worlds should be between 0 and 0.2.",
  "planet-semi-major-btn":"The average separation between the planet and its parent star in AUs.</br>Habitable planets should have semi-major axis in parents star habitable zone.",
  "planet-semi-minor-btn":"The shorter radius of ecliptical orbit of planet and its parent star in AUs.",
  "planet-periapsis-btn":"The closest the planet gets to its parent star in AUs.</br>A habitable planet needs to have this land inside the parents habitable zone.",
  "planet-apoapsis-btn":"The farthest the planet gets from its parent star in AUs.</br>A habitable planet needs to have this land inside the parents habitable zone.",
  "planet-period-btn":"The length of a planets orbit relitive to that of Earth's.",
  "planet-year-btn":"The lenth of a planets year in Earth days.",
  "planet-velocity-btn":"The oribtial velocity relitive to that of Earth's.",
  "planet-hill-inner-btn":"The Inner Hill Sphere, aka the closest a moon / satalite can orbit the planet.",
  "planet-hill-outer-btn":"The Inner Hill Sphere, aka the Furthest a moon / satalite can orbit the planet",
  "planet-day-hours-btn":"The length of a local day in Earth hours.",
  "planet-year-local-btn":"The length of a local year in local days.",
  "planet-months-year-btn":"The number of local months per local year.",
  "planet-day-month-btn":"How many local days per local month.",
  "planet-hour-day-btn":"The number of local hours per local day.",
  "planet-hour-hour-btn":"The number of local hours per Earth hour.",
  "planet-min-hour-btn":"The number of local minutes per local hour.",
  "planet-min-min-btn":"The number of local minutes per Earth minute.",
  "planet-sec-min-btn":"The number of local seconds per local minute.",
  "planet-sec-sec-btn":"The number of local seconds per Earth second.",
}